Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\d2c\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\envs\d2c\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\envs\d2c\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\envs\d2c\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\envs\d2c\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\envs\d2c\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\envs\d2c\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\envs\d2c\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys
sys.path.append("..")
from d2c.SimulatedTimeSeries import SimulatedTimeSeries

# Initialize the SimulatedDAGs object
simulated_timeseries = SimulatedTimeSeries(1, 10, 7)
simulated_timeseries.generate_time_series()
DAG = simulated_timeseries.get_dags()[0]

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m
[0;32m      2[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend([38;5;124m"[39m[38;5;124m..[39m[38;5;124m"[39m)
[1;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01md2c[39;00m[38;5;21;01m.[39;00m[38;5;21;01mSimulatedTimeSeries[39;00m [38;5;28;01mimport[39;00m SimulatedTimeSeries
[0;32m      5[0m [38;5;66;03m# Initialize the SimulatedDAGs object[39;00m
[0;32m      6[0m simulated_timeseries [38;5;241m=[39m SimulatedTimeSeries([38;5;241m1[39m, [38;5;241m10[39m, [38;5;241m7[39m)

[1;31mModuleNotFoundError[0m: No module named 'd2c.SimulatedTimeSeries'
ModuleNotFoundError: No module named 'd2c.SimulatedTimeSeries'

